language: haskell
cabal: "2.4"

matrix:
  include:
  - &bionic
    ghc:  "8.0.2"
  - &buster
    ghc:  "8.4.4"
  - &unstable
    ghc:  "8.6.5"
  - &experimental
    ghc:  "8.8.1"
    cabal:  "3.0"

  - <<: *bionic
    env: WARNALL=yes
  - <<: *buster
    env: WARNALL=yes
  - <<: *unstable
    env: WARNALL=yes
  - <<: *experimental
    env: WARNALL=yes

  allow_failures:
  - env: WARNALL=yes
  fast_finish: true

env:
- WARNALL=no

install: |
  (
    set -xe
    cabal v2-update
  )

script: |
  (
    set -xe
    cabal_build() {
      cabal v2-build --write-ghc-environment-files=always --enable-tests
    }
    if [ "$WARNALL" = yes ]; then
      sed -i 's/-fno-warn-unused-imports//' koneko.cabal
      cabal_build || {
        sed -i 's/-Werror//' koneko.cabal
        cabal_build
        false
      }
    else
      cabal_build
    fi

    cabal v2-run doctests   # nicer output than v2-test
    cabal v2-run koneko -- --doctest lib/*.knk README.md

    nvm use v11.0.0
    node js/koneko.js --doctest lib/*.knk README.md
  )

cache:
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
