language: haskell
matrix:
  include:
    - cabal:  "2.4"
      ghc:  "8.0.2" # bionic
    - cabal:  "2.4"
      ghc:  "8.4.4" # buster
    - cabal:  "2.4"
      ghc:  "8.6.5" # unstable
    - cabal:  "3.0"
      ghc:  "8.8.1" # experimental
install: |
  set -e
  cabal v2-update
script: |
  set -e
  cabal v2-build --write-ghc-environment-files=always --enable-tests
  cabal v2-test
cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
