language: haskell
matrix:
  include:
    - cabal:  "2.4"
      ghc:  "8.0.2" # bionic
    - cabal:  "2.4"
      ghc:  "8.4.4" # buster
    - cabal:  "2.4"
      ghc:  "8.6.5" # unstable
    - cabal:  "3.0"
      ghc:  "8.8.1" # experimental
  allow_failures:
    - ghc:  "8.0.2"
    - ghc:  "8.8.1"
  fast_finish: true
install: |
  set -e
  cabal v2-install --only-dependencies
  cabal v2-install doctest
script: |
  set -e
  export PATH=~/.cabal/bin:"$PATH"
  cabal v2-build
  doctest src/
cache:
  directories:
    - $HOME/.cabal
